### ISSUE TITLE
No soporta nombres de tablas con mayúsculas 

### ISSUE THREAD

**Issue by hernandanielg** [DavidAH01/auto_forms#2]
Si utilizo nombres en mayúscula para las bases de datos me aparece un error.

![2016-08-19-17 10 28-screenshot](https://cloud.githubusercontent.com/assets/7015094/17826120/497e3310-6633-11e6-8b53-37f7e2dbc3f8.png)

**Comment by DavidAH01** [comment]
Se hizo así para mantener un estándar entre el nombre de las tablas y el nombre de los campos dentro de ellas. 
Todo se debe escribir en minúsculas y los espacios se reemplazan por guiones bajos (_)
